#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'cutadapt==1.12','console_scripts','cutadapt'
__requires__ = 'cutadapt==1.12'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('cutadapt==1.12', 'console_scripts', 'cutadapt')()
    )
